name: check
on: push
jobs:
  lint:
    name: lint
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Install swiftlint
        run: |
          brew install swiftlint
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
      - name: Code Lint
        run: |
          swiftlint --strict
      - name: Install iblinter
        run: |
          brew install IBDecodable/homebrew-tap/iblinter
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
      - name: Storyboard Lint
        run: |
          iblinter lint
      - name: Install jsonlint
        run: |
          brew install jsonlint | tee
      - name: Manifest Lint
        run: |
          cat manifest.json | jsonlint
  build:
    name: build
    runs-on: macOS-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Swift build
        run: |
          sdk=`xcrun -sdk iphonesimulator -show-sdk-path`
          sdkVersion=`echo $sdk | sed -E 's/.*iPhoneSimulator(.*)\.sdk/\1/'`
          swift build  -Xswiftc "-sdk" -Xswiftc "$sdk" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios$sdkVersion-simulator"
